spring:
  jackson:
    serialization:
      indent-output: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    open-in-view: off
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  mvc:
    log-request-details: true
server:
  port: 8080
  servlet:
    register-default-servlet: true
logging:
  level:
    org:
      springframework:
        web:
          filter:
            CommonRequestLoggingFilter: TRACE
    org.springframework.web: trace

